##
## EPITECH PROJECT, 2018
##
## File description:
##
##

all:
	make -C ./pacman/
	make -C ./centipede/
	make -C ./nibbler/

re:	fclean all

clean:
	make clean -C ./pacman/
	make clean -C ./centipede/
	make clean -C ./nibbler/

fclean:
	make fclean -C ./pacman/
	make fclean -C ./centipede/
	make fclean -C ./nibbler/
