##
## EPITECH PROJECT, 2018
##
## File description:
##
##

all:
	make -C ./sdl/
	make -C ./opengl/
	make -C ./caca/

re:	fclean all

clean:
	make clean -C ./sdl/
	make clean -C ./opengl/
	make clean -C ./caca/

fclean:
	make fclean -C ./sdl/
	make fclean -C ./opengl/
	make fclean -C ./caca/

