##
## EPITECH PROJECT, 2018
## 
## File description:
## 
##

all:
	make -C ./graplib/sdl/
	make -C ./graplib/opengl/
	make -C ./graplib/caca/

re:	fclean all

clean:
	make clean -C ./graplib/sdl/
	make clean -C ./graplib/opengl/
	make clean -C ./graplib/caca/

fclean:
	make fclean -C ./graplib/sdl/
	make fclean -C ./graplib/opengl/
	make fclean -C ./graplib/caca/
